export default {
    products: [
        {
            id: 1,
            image: 'http://localhost:5000/img/product6.jpg',
            price: 12,
            review: 5,
            title: 'Rajshahi Mango',
            category: 'fruit',
            featured: true,
            newS: false,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 12,
            best: true
        },
        {
            id: 2,
            image: 'http://localhost:5000/img/product4.jpg',
            price: 3,
            review: 4,
            title: 'Fresh Cofy',
            category: 'veg',
            featured: true,
            newS: false,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 3,
            best: true
        },
        {
            id: 3,
            image: 'http://localhost:5000/img/product11.jpg',
            price: 13,
            review: 5,
            title: 'Grape Fruit',
            category: 'grape',
            featured: false,
            newS: false,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 13,
            best: true
        },
        {
            id: 4,
            image: 'http://localhost:5000/img/product22.jpg',
            price: 2.8,
            review: 5,
            title: 'Onion Mosorio',
            category: 'veg',
            featured: true,
            newS: false,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 2.8,
            best: true
        },
        {
            id: 5,
            image: 'http://localhost:5000/img/product1.jpg',
            price: 18,
            review: 5,
            title: 'Reed Grape Fruites',
            category: 'grape',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 18,
            best: false
        },
        {
            id: 6,
            image: 'http://localhost:5000/img/product10.jpg',
            price: 18,
            review: 5,
            title: 'Foreign Chili',
            category: 'veg',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 18,
            best: true
        },
        {
            id: 7,
            image: 'http://localhost:5000/img/product24.jpg',
            price: 1.8,
            review: 4,
            title: 'Banana',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 1.8,
            best: false
        },
        {
            id: 8,
            image: 'http://localhost:5000/img/product23.jpg',
            price: 2.3,
            review: 4,
            title: 'Anarosh - Deshi',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 2.3,
            best: false
        },
        {
            id: 9,
            image: 'http://localhost:5000/img/product12.jpg',
            price: 2.6,
            review: 5,
            title: 'Anar (Paris)',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 2.6,
            best: true
        },
        {
            id: 10,
            image: 'http://localhost:5000/img/product2.jpg',
            price: 3.6,
            review: 4,
            title: 'Watermelon',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 3.6,
            best: false
        },
        {
            id: 11,
            image: 'http://localhost:5000/img/product5.jpg',
            price: 7,
            review: 5,
            title: 'kijani',
            category: 'veg',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 7,
            best: false
        },
        {
            id: 12,
            image: 'http://localhost:5000/img/product9.jpg',
            price: 11.9,
            review: 5,
            title: 'Green Apple',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 11.9,
            best: false
        },
        {
            id: 13,
            image: 'http://localhost:5000/img/product1.jpg',
            price: 19.9,
            review: 5,
            title: 'Canadian Grape',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 19.9,
            best: false
        },
        {
            id: 14,
            image: 'http://localhost:5000/img/product3.jpg',
            price: 12.3,
            review: 4,
            title: 'Malta',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 12.3,
            best: false
        },
        {
            id: 15,
            image: 'http://localhost:5000/img/product15.jpg',
            price: 7,
            review: 5,
            title: 'Deshi Onion',
            category: 'veg',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 7,
            best: false
        },
        {
            id: 16,
            image: 'http://localhost:5000/img/product25.jpg',
            price: 34,
            review: 5,
            title: 'Papaya',
            category: 'fruit',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 34,
            best: false
        },
        {
            id: 17,
            image: 'http://localhost:5000/img/product16.jpg',
            price: 9.2,
            review: 5,
            title: 'Gajor',
            category: 'veg',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 9.2,
            best: false
        },
        {
            id: 18,
            image: 'http://localhost:5000/img/product13.jpg',
            price: 6,
            review: 5,
            title: 'Kala Grape Fruit',
            category: 'grape',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 6,
            best: false
        },
        {
            id: 19,
            image: 'http://localhost:5000/img/product11.jpg',
            price: 13,
            review: 5,
            title: 'Canadian Grape',
            category: 'grape',
            featured: false,
            newS: false,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 13,
            best: false
        },{
            id: 20,
            image: 'http://localhost:5000/img/product1.jpg',
            price: 18,
            review: 5,
            title: 'Reed Grape Fruites',
            category: 'grape',
            featured: true,
            newS: true,
            short_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            long_des: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae ea reprehenderit tempora itaque eveniet, excepturi impedit autem ipsam nemo laborum ad optio totam similique qui.',
            qty: 1,
            total: 18,
            best: false
        }
    ]
}